### ISSUE TITLE
host path missing; path for shell provisioner does not exist

### ISSUE THREAD

**Issue by glerner** [Chassis/Chassis#314] opened 2017-01-15 05:24 UTC
No errors from git clone.
Several errors on vagrant up
-  host path of the shared folder is missing
- `path` for shell provisioner does not exist on the host system
Windows 10, Oracle VirtualBox Version 5.1.12 r112440 (Qt5.6.2), Vagrant 1.9.1
Administrator: Windows PowerShell

PS C:\home\glvagrant> git clone --recursive https://github.com/Chassis/Chassis chassistest
Cloning into 'chassistest'...
remote: Counting objects: 10550, done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 10550 (delta 27), reused 0 (delta 0), pack-reused 10495
Receiving objects: 100% (10550/10550), 27.71 MiB | 999.00 KiB/s, done.
Resolving deltas: 100% (6709/6709), done.
Checking connectivity... done.
Checking out files: 100% (1764/1764), done.
Submodule 'puppet/modules/apt' (https://github.com/puppetlabs/puppetlabs-apt.git) registered for path 'puppet/modules/apt'
Submodule 'puppet/modules/mysql' (https://github.com/puppetlabs/puppetlabs-mysql.git) registered for path 'puppet/modules/mysql'
Submodule 'puppet/modules/stdlib' (https://github.com/puppetlabs/puppetlabs-stdlib.git) registered for path 'puppet/modules/stdlib'
Submodule 'puppet/modules/wp' (https://github.com/rmccue/puppet-wp.git) registered for path 'puppet/modules/wp'
Cloning into 'puppet/modules/apt'...
remote: Counting objects: 4694, done.
remote: Compressing objects: 100% (11/11), done.
Receiving objects: 100% (4694/4694), 1.03 MiB | 636.00 KiB/s, done.
emote: Total 4694 (delta 2), reused 0 (delta 0), pack-reused 4683
Resolving deltas: 100% (2674/2674), done.
Checking connectivity... done.
Submodule path 'puppet/modules/apt': checked out '1d20fa798ea3f32e195f1d950f1f53cb188c2705'
Cloning into 'puppet/modules/mysql'...
remote: Counting objects: 6297, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 6297 (delta 0), reused 0 (delta 0), pack-reused 6294Receiving objects: 100% (6297/6297), 1.03 MiB | 414.00Receiving objects: 100% (6297/6297), 1.34 MiB | 414.00 KiB/s, done.
Resolving deltas:   4% (138/3338)
Resolving deltas: 100% (3338/3338), done.
Checking connectivity... done.
Submodule path 'puppet/modules/mysql': checked out 'e2f3b54565e66693dd5a6617a45ccdddf2f5e977'
Cloning into 'puppet/modules/stdlib'...
remote: Counting objects: 9257, done.
remote: Compressing objects: 100% (12/12), done.
Rremote: Total 9257 (delta 0), reused 0 (delta 0), pack-reused 9244eceiving objects:  99% (9165/9257), 1.67 MiB | 669.00 KiB/s
Receiving objects: 100% (9257/9257), 1.85 MiB | 669.00 KiB/s, done.
Resolving deltas: 100% (4442/4442), done.
Checking connectivity... done.
Submodule path 'puppet/modules/stdlib': checked out '2a78cbfaad2acc61d6d8bab715db00c9890adbd7'
Cloning into 'puppet/modules/wp'...
remote: Counting objects: 239, done.
Receiving objects: 100% (239/239), 31.41 KiB | 0 bytes/s, done.
emote: Total 239 (delta 0), reused 0 (delta 0), pack-reused 239
Resolving deltas: 100% (111/111), done.
Checking connectivity... done.
Submodule path 'puppet/modules/wp': checked out '73d5a105e1e306d98e1cd29ecdf77051d0ba2653'

PS C:\home\glvagrant> cd chassistest
PS C:\home\glvagrant\chassistest> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The host path of the shared folder is missing: database/
* The host path of the shared folder is missing: config/
* The host path of the shared folder is missing: log/
* The host path of the shared folder is missing: www/

shell provisioner:
* `path` for shell provisioner does not exist on the host system: C:/home/glvagrant/chassistest/provision/provision.sh
* `path` for shell provisioner does not exist on the host system: C:/home/glvagrant/chassistest/provision/provision-utility-source.sh
* `path` for shell provisioner does not exist on the host system: C:/home/glvagrant/chassistest/provision/provision-utility.sh
* `path` for shell provisioner does not exist on the host system: C:/home/glvagrant/chassistest/provision/provision-utility.sh
* `path` for shell provisioner does not exist on the host system: C:/home/glvagrant/chassistest/provision/provision-utility.sh
* `path` for shell provisioner does not exist on the host system: C:/home/glvagrant/chassistest/provision/provision-utility.sh
* `path` for shell provisioner does not exist on the host system: C:/home/glvagrant/chassistest/provision/provision-site.sh
* `path` for shell provisioner does not exist on the host system: C:/home/glvagrant/chassistest/provision/provision-site.sh

**Comment by BronsonQuick** [comment] 2017-01-16 04:14
@cameronjonesweb Are you still running a Chassis box on Windows 10? If so any chance you might be able to look into this for me?

I have an old Windows 8.1 laptop at home which I spun up and started looking into this but I got a different error.

@glerner I might be able to download a VirtualBox image of Windows 10 on the weekend and debug it that way for you.

**Comment by cameronjonesweb** [comment] 2017-01-16 04:20
Yeah I'm still running on Windows 10, haven't ever run into that before. I'll see if I can take a look and try to replicate it tonight

**Comment by BronsonQuick** [comment] 2017-01-16 05:02
@cameronjonesweb Awesome. Thanks very much!

**Comment by cameronjonesweb** [comment] 2017-01-17 09:08
I've been testing it and haven't been able to replicate it but I am using Vagrant 1.8.1 so I'll update to 1.9.1 and see how I go

**Comment by BronsonQuick** [comment] 2017-01-17 11:53
@cameronjonesweb Awesome. Thanks dude! I've got a VM setup. I haven't found time to test it yet. The VM for Windows 10 was 20 gig!

**Comment by BronsonQuick** [comment] 2017-01-17 11:54
@glerner Just wondering if you'd made any customisation to any of the yaml files too? If so can you please attach those for us! Thanks!

**Comment by cameronjonesweb** [comment] 2017-01-18 06:27
I updated Vagrant and VirtualBox to match the versions and still couldn't reproduce. I do have the [hostsupdater](https://github.com/cogitatio/vagrant-hostsupdater) plugin installed, would you be able to try installing it and trying again?

And as Bronson mentioned, if you've got any custom config files it would be much appreciated if you could send them over.

This might sound like a silly suggestion, but has your PC been rebooted since installing Vagrant and VirtualBox? Just want to cover the bases.

**Comment by BronsonQuick** [comment] 2017-06-25 20:15
I'm going to close this issue out since we haven't had any more feedback. Thanks heaps @cameronjonesweb for testing this on your Windows machine for us!

**Closed by BronsonQuick** 2017-06-25 20:15 UTC
