### ISSUE TITLE
Use trusty64 instead precise64?

### ISSUE THREAD

**Issue by tikot** [Chassis/Chassis#130] opened 2015-04-24 04:05 UTC
What is the reason to use `precise64`?

I have recently tried to boot up Chassis could not get it to work. Changed box to `ubuntu/trusty64` boots up with out any problems. 

Should I submit a pull request to update box config to `ubuntu/trusty64` in Chassis/Vagrantfile line number 69

**Comment by BronsonQuick** [comment] 2015-04-24 04:33
Hey @tikot,

Can you please let me know what you couldn't get to work with `precise64`? Can you please uncomment: https://github.com/Chassis/Chassis/blob/master/Vagrantfile#L102 and post the output for me here please so we can work out what didn't work for you?

The main reason we have `precise64` is because when we started Chassis it was the last LTS release as well as the fact that it's the default Vagrant box some most people already have that base box on their machine.

That being said we are now keen to update to trusty too so a PR would be great thanks :+1: We'd still like to get to the bottom of your `precise64` issue too though! Thanks :smiley:

**Comment by tikot** [comment] 2015-04-24 07:09
Hey @BronsonQuick,

Here the log https://gist.github.com/tikot/4dc948e354df3a9f2598

**Comment by BronsonQuick** [comment] 2015-04-24 07:21
@rmccue Any thoughts on this one?

@tikot What version of Windows are you using? Also can you please let me know the versions of Vagrant and VirtualBox you're using? If they aren't the latest can you please try upgrading them?

It's a shame I left my Windows laptop in the office otherwise I could try and reproduce it. Thanks again! Hopefully we can get to the bottom of it!

**Comment by tikot** [comment] 2015-04-24 07:30
@BronsonQuick Latest version on everything.
Vagrant 1.7.2
VirtualBox 4.3.26r98988
Windows 8.1 x64

**Comment by tikot** [comment] 2015-04-27 18:46
Mac (log)[https://gist.github.com/tikot/e2ea8b91e879bef3d1fc] with php 5.5 config.yaml

Vagrant 1.7.2
VirtualBox 4.3.26r98988
OS X 10.10.3

I think I know what is the issue it is something with php https://github.com/Chassis/Chassis/pull/131#issuecomment-96450342

**Comment by BronsonQuick** [comment] 2016-04-22 01:52
I still haven't been able to replicate this one so I'll close it out.

**Closed by BronsonQuick** 2016-04-22 01:52 UTC
Labels: enhancement
